version: '3.9'
services:
  social-recovery-service:
    image: docker.swaywallet.io/social-recovery-service:latest
    build:
      context: packages/social-recovery-service
      dockerfile: Dockerfile
      args:
        appPort: ${SOCIAL_RECOVERY_SERVICE_PORT}
        nodeVersion: ${NODE_VERSION}
    ports:
      - ${SOCIAL_RECOVERY_SERVICE_PORT}:${SOCIAL_RECOVERY_SERVICE_PORT}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  guardian-service:
    image: docker.swaywallet.io/guardian-service:latest
    build:
      context: packages/guardian-service
      dockerfile: Dockerfile
      args:
        appPort: ${GUARDIAN_SERVICE_PORT}
        nodeVersion: ${NODE_VERSION}
    ports:
      - ${GUARDIAN_SERVICE_PORT}:${GUARDIAN_SERVICE_PORT}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  social-recovery-ui:
    image: docker.swaywallet.io/social-recovery-ui:latest
    build: 
      context: apps
      dockerfile: Dockerfile
      args:
        appPort: ${SOCIAL_RECOVERY_UI_PORT}
        nodeVersion: ${NODE_VERSION}
    ports:
      - ${SOCIAL_RECOVERY_UI_PORT}:${SOCIAL_RECOVERY_UI_PORT}
    env_file:
      - .env
  postgres:
    image: postgres:16.1-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'social-recovery-service']
      interval: 5s
      timeout: 10s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres:
    driver: local
  pgadmin-data:
    driver: local
