version: '3.8'
services:
  guardian-service:
    # image: docker.swaywallet.io/guardian-service:latest
    build: .
    ports:
      - '8200:8200'
    depends_on:
      - db
  db:
    image: postgres:16.1-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db:
    driver: local
  pgadmin-data:
    driver: local
